//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class QProcess_Win64 {
  public static int Execute3(string exe, string args, string cwd) {
    int ret = QProcess_Win64PINVOKE.Execute3(exe, args, cwd);
    if (QProcess_Win64PINVOKE.SWIGPendingException.Pending) throw QProcess_Win64PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int Execute4(bool windowed, string exe, string args, string cwd) {
    int ret = QProcess_Win64PINVOKE.Execute4(windowed, exe, args, cwd);
    if (QProcess_Win64PINVOKE.SWIGPendingException.Pending) throw QProcess_Win64PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void Launch3(string exe, string args, string cwd) {
    QProcess_Win64PINVOKE.Launch3(exe, args, cwd);
    if (QProcess_Win64PINVOKE.SWIGPendingException.Pending) throw QProcess_Win64PINVOKE.SWIGPendingException.Retrieve();
  }

}
